### ISSUE TITLE
Improve Dashboard design

### ISSUE THREAD

**Issue by tomjanssens** [joomlatools/joomlatools-vagrant#13]
- [x] Implement Grunt
- [x] Change title to 'Joomlatools Vagrant'
- [x] Appify using iFrames so navigation stays in place
- [x] Switch Tools with System and rename the items in the Tools menu to:
  - Info
  - Logs
  - Files
  - Terminal
- [x] Not working properly on small screens
- [x] Add `$cfg['AllowThirdPartyFraming'] = true;` to `config.inc.php` to allow phpMyAdmin to open in an iFrame
- [x] MailCatcher doesn't open in an iFrame because `X-Frame-Options` is set to `SAMEORIGIN`
- [x] Remove redirect to `/dashboard` it is now available from the root folder: http://joomla.box/joomlatools-vagrant/puppet/modules/scripts/files/scripts/
- [x] Add links to Gitter for support

Instructions on how to easily work on the dashboard HTML can be found in the [wiki](https://github.com/joomlatools/joomlatools-vagrant/wiki/Working-on-the-dashboard-layout).

**Comment by tomjanssens** [comment]
@stevenrombauts can you give it a try? And have a look at the last two points in the description?

**Comment by tomjanssens** [comment]
Horizontal scrollable navigation has been added for small viewports.

![localhost-5666-joomlatools-vagrant-puppet-modules-scripts-files-scripts- iphone 5](https://cloud.githubusercontent.com/assets/700063/17697902/02df575e-63b8-11e6-979b-99919f7d32ec.png)

**Comment by stevenrombauts** [comment]
@tomjanssens This is working great! Much better now :) I fixed two items of your list (phpmyadmin + dashboard redirect), but we can't do anything about the Mailcatcher issue. I'll be replacing Mailcatcher with Mailhog anyway, so maybe that will fix it automatically. If not, we'll just have to link directly.

**Comment by johanjanssens** [comment]
@tomjanssens Can we also add the command line to the dashboard for larger screens so it's available immediately? This saves an extra click and  window.

**Comment by tomjanssens** [comment]
@johanjanssens this would be a drastic change not part of the scope of this issue. The UI is tab-based and won't open a new window for the terminal so that will be already solved. Let's focus on the remaiming tasks at hand.
