### ISSUE TITLE
Requested NFS version or transport protocol is not supported

### ISSUE THREAD

**Issue by JurgenG** [joomlatools/joomlatools-vagrant#132]
### Describe your environment

  * OS: Ubuntu 18.04 64 bits
  * Joomla version: 3.8.11 (irrelevant)
  * Joomlatools Vagrant version: 2.1.2

### Describe the problem:
In the first launch of the Vagrant box, the install fails with the error

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3,udp,rw,tcp,nolock,noacl,async 33.33.33.1:/home/jurgen/vagrant/joomla.box/www /var/www

Stdout from the command:



Stderr from the command:

mount.nfs: requested NFS version or transport protocol is not supported
```
I solved the issue by manually starting the nfs service (sudo service nfs start) but I can imagine a test for this would be in place and the service should be launched by the installer.

#### Steps to reproduce:

  1. vagrant init joomlatools/box and then vagrant up
  2. wait...

#### Observed Results:
See above

#### Expected Results:
The vagrant box would work just fine

#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

#### Possibly relevant
I'm already running other webservers in /var/www

**Comment by tassosm** [comment]
I am also facing this issue on Ubuntu 18.04.2 LTS with vagrant 2.2.4

The issue started after some updates got installed today.

I also solved it by running sudo service nfs-kernel-server start

**Comment by stevenrombauts** [comment]
Thanks for pointing this out. We've added the Ubuntu requirement to the set up instructions: https://www.joomlatools.com/developer/tools/vagrant/getting-started#installation
