### ISSUE TITLE
Update Nodejs version

### ISSUE THREAD

**Issue by ercanozkaya** [joomlatools/joomlatools-vagrant#138]
Current install Nodejs is the Ubuntu default and is v0.10.x 

Update this to the latest stable release. 

Ideally use [NVM](https://github.com/creationix/nvm) to install so that we can easily update in the feature without a box upgrade)

We need at least these versions:

```
$ node -v
v10.15.3

$ npm -v
6.4.1
```

Precedes #148

**Comment by stevenrombauts** [comment]
Note to self: test with static site assets compilation.
