### ISSUE TITLE
Install Cockpit

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/joomlatools-vagrant#139]
Install https://cockpit-project.org/

**Comment by yiendos** [comment]
### Notes 

Support for cockpit comes out of the box with Ubuntu 18.04. 

https://cockpit-project.org/guide/latest/


https://www.itzgeek.com/how-tos/linux/ubuntu-how-tos/install-cockpit-on-ubuntu-16-04.html


https://www.digitalocean.com/community/tutorials/how-to-install-linux-dash-on-ubuntu-14-04



Used these steps:
https://askubuntu.com/questions/488816/installation-guide-for-multiple-servers-using-cockpit


To come up with the following: 

```

sudo add-apt-repository ppa:jpsutton/cockpit
apt::ppa { 'ppa:jpsutton/cockpit': }

sudo apt-get update
apt::update

sudo apt-get install cockpit
apt::source { 'cockpit': }

sudo apt-get install glib-networking
apt::source { 'glib-networking': }


sudo /usr/sbin/remotectl certificate --ensure --user=root

exec { 'remotectl certificate':
  command => "/usr/sbin/remotectl certificate --ensure --user=root",
  path    => ['/usr/bin' , '/bin', '/usr/sbin/'],
  creates => '/etc/cockpit/ws-certs.d/~self-signed.cert'
}

#sudo /usr/libexec/cockpit-ws
```

### Note still need to start this as the system starts

**Comment by yiendos** [comment]
## Notes to self for re-building box 

Destroy the box: 

`vagrant halt` 

`vagrant destroy` 

Remove puppet/modules leaving the .gitignore 

Remove puppet.tmp folder 

`vagrant up`

add the following file to the vagrant box 

`touch /tmp/mysql.key` 

`nano /tmp/mysql.key` 

copy paste of mysql.key 

`sudo apt-key add /tmp/mysql.key`

might have to try this a few times 

`vagrant provision --provision-with=puppet `

might need to do this a couple of times

**Comment by yiendos** [comment]
@stevenrombauts okie works after a few provisions... the first couple seem to fail and then it automagically works eventually. I've managed to side step the need for  `https://` for cockpit here:
https://github.com/joomlatools/joomlatools-vagrant/commit/1ffa6919893c03bd6a4964037de6625ea9c4305e#diff-cd477e7da9766b4d715fc8ab54684c47R28

So the admin area can now be accessed through `http://joomla.box:9090`
