### ISSUE TITLE
Small issue in Administrator url

### ISSUE THREAD

**Issue by javigomez** [joomlatools/joomlatools-vagrant#15]
This is a very minor issue, not really affecting the behaviour of the button, but the Administrator url has a duplicated `/`:

![capture 2016-01-03 at 17 21 23](https://cloud.githubusercontent.com/assets/1375475/12619914/6c97dd70-c51a-11e5-9bbd-4e1ad062829f.png)

https://github.com/joomlatools/joomlatools-vagrant/blob/51f1c803f25b4feadb33a343c29a1a432dc2e446/puppet/modules/scripts/files/scripts/dashboard/index.php#L175

**Comment by johanjanssens** [comment]
@javigomez Could you do a PR for this ? Thanks!

**Comment by javigomez** [comment]
sure!. I'll send a pull in a while.

^_^

**Comment by johanjanssens** [comment]
Thanks @javigomez very much appreciated!
