### ISSUE TITLE
Incorrect host permissions over site files 

### ISSUE THREAD

**Issue by yiendos** [joomlatools/joomlatools-vagrant#150]
### Describe the problem:

When you create a new Joomla site via the console command, the site is created... but the host site files have an incorrect `user:group` permissions applied. 

This only becomes apparent, when you try to edit the files in your IDE of choice. The permissions effectively lock the site files, and with phpStorm you can't even import the site files into a new project. 

#### Steps to reproduce:

1.  Spin up a new version of the JT-Vagrant box
2. Install a site `joomla site:create testing` 
3. Attempt to drag and drop site finder folder into phpstorm

#### Observed Results:

Instead of phpstorm opening the project files, nothing happens. Checking the permissions over the newly created folder: 
```
→ ls -la 
total 16
drwxr-xr-x   9 root       wheel   288 13 Jun 08:46 .
drwxr-xr-x  27 example	  staff   864  6 Jun 15:57 ..
drwxrwxr-x  30 example	  staff   960 13 Jun 08:40 joomlatools
drwxrwxr-x  23 root       wheel   736 13 Jun 08:59 testing
```
Note: applying the correct permissions of `example:staff` over the joomlatools folders means that the IDE is able to import and edit the files. 

Where as the `root:wheel` permissions are incorrectly applied to testing

**Comment by stevenrombauts** [comment]
@yiendos Correct, I've fixed this yesterday in https://github.com/joomlatools/joomlatools-vagrant/commit/bd7219b5b97292ef8e56cd8b01d5594ee453cf83
