### ISSUE TITLE
Install YellowLab tools

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/joomlatools-vagrant#157]
Add the entire YellowLabs application to be able to run tests locally without having to deploy it first.

See:
* https://github.com/gmetais/YellowLabTools

##  Edit - Following discussions on Slack - 19th November 2019 

We are first going to attempt to install the command line interface first: 
https://github.com/gmetais/YellowLabTools/wiki/Command-Line-Interface

See if this avoids the heavy install process for the whole software package: 
https://github.com/gmetais/YellowLabTools/wiki/Install-your-private-server

**Comment by yiendos** [comment]
## Notes

* run a test on the local site and save the output to a file 
`yellowlabtools http://joomlatools.test > /var/www/joomlatools.test.results.json` 
* run a test on the local site and save a screenshot 
`yellowlabtools http://joomlatools.test --screenshot=/var/www/joomlatools-test.png`
