### ISSUE TITLE
Joomla.box is not in hosts of the vagrant machine

### ISSUE THREAD

**Issue by javigomez** [joomlatools/joomlatools-vagrant#16]
Hi, I'm not skilled in vagrant and I'm not sure about the right way to to fix this, let me explain the issue:

![capture 2016-01-04 at 14 02 05](https://cloud.githubusercontent.com/assets/1375475/12645085/c4a1357c-c5c7-11e5-8c68-27b4c3a03dac.png)

Of course if I do a curl from the host (MacOS) it works because I have it in hosts:

![screen shot 2016-01-28 at 14 05 24](https://cloud.githubusercontent.com/assets/1375475/12645134/3479feec-c5c8-11e5-8453-fbb018a67114.png)

However if I do a curl from the Vagrant ssh:

![screen shot 2016-01-28 at 14 06 05](https://cloud.githubusercontent.com/assets/1375475/12645166/6ce62fee-c5c8-11e5-8193-b07ea0fb1a7b.png)

I guess the solution is adding joomla.box as host in the Vagrant machine but not sure.

I must say that this was not an issue in `joomla-vagrant`, is only happening in `joomlatools-vagrant`. 

If you can point me to the right place, I'm happy to test and send a fix.
Thanks

**Comment by johanjanssens** [comment]
@javigomez thanks for the excellent bug report. This helps a lot. This sounds to be an issue that also goes over my head. Assigned it to @stevenrombauts our box master. Steven is currently enjoying a well deserved holiday, he will look into it when he is back.

**Comment by javigomez** [comment]
A manual way to solve:

`vagrant ssh`

`sudo vi /etc/hosts`

modify the line:

```
127.0.1.1       joomlatools 
```

for:

```
127.0.1.1       joomlatools joomla.box
```

Save and exit `vi` editor

Reestart the server with:

`box server:restart`

The issue should be fixed
