### ISSUE TITLE
GPG errors 

### ISSUE THREAD

**Issue by bark100** [joomlatools/joomlatools-vagrant#17]
I'm getting GPG validation errors when puppet tries to provision the VM. 

This in turns causes apt to fail installing packages and until provisioning fails. 

Does anyone else has issues with GPG keys?

**Comment by johanjanssens** [comment]
Please do not use the Github issues to ask questions. If you do have a problem running the box please use either [our forum](https://groups.google.com/forum/#!forum/joomlatools-dev) or [chat room](http://gitter.im/joomlatools/dev) to get in touch with us and we are most happy to try and help you.
