### ISSUE TITLE
504 timeout

### ISSUE THREAD

**Issue by tonypartridge** [joomlatools/joomlatools-vagrant#173]
I'm noticing huge issues with the latest releases with 504 timeouts. Initially I thought it was just a heavy script, but actually it's even on a basic joomla site. 

Any suggestions? At present I am tempted to just build my own dev stack.

**Comment by johanjanssens** [comment]
@tonypartridge For questions please use our community support channels:

- forum: https://groups.google.com/forum/#!forum/joomlatools-dev
- chat: http://gitter.im/joomlatools/dev

Thanks!

**Comment by stevenrombauts** [comment]
@tonypartridge We haven't run into such a problem yet, except one of our team who has issues with large file uploads. You can always check in Cockpit to see if something might be eating up your available memory or using too much CPU time. If you're box is running, you can access that here: 


You can try to increase available memory from the start by overriding the custom configuration, see [How can I change my Virtualbox settings](https://www.joomlatools.com/developer/tools/vagrant/faq#how-can-i-change-my-virtualbox-settings) in the FAQ.  If you add the following to your `config.custom.yaml` file, it will double the available memory on the box:

```
virtualbox:
  memory: 2048
```

Let us know on our Gitter chat if that helped or not!

**Comment by tonypartridge** [comment]
I completely forgot about cockpit doh! I've got loads of resources so just increased the CPU and Mem anyway.

**Comment by johanjanssens** [comment]
Thats great to hear @tonypartridge. In future feel free to jump into our chat. Easier to assist you there, we like to keep the Github issues for PR and actual development work.

Also, not sure if you are aware already but I have been working on a new developer tool for Joomla called Joomlatools Pages, like our Vagrant box, it's completely free. You can find more info here: https://github.com/joomlatools/joomlatools-pages/wiki

We use it to build Joomlatools.com, getting started is super easy:

- https://github.com/joomlatools/joomlatools-pages/wiki/Installation
- https://github.com/joomlatools/joomlatools-pages/wiki/Getting-Started

To get an idea what it can do: https://github.com/joomlatools/joomlatools-pages/wiki/Basics

Love to hear your feedback!
