### ISSUE TITLE
Vagrant can't install guest additions

### ISSUE THREAD

**Issue by javigomez** [joomlatools/joomlatools-vagrant#20]
Hi, not sure if is an error of the Vagrant Box.

I have a host machine Mac OSX El Capitan 10.11.3
Latest Vagrant 1.8.1
VirtualBox 5.0.14

When executing `vagrant up` I have this error:

![screen shot 2016-02-03 at 10 52 42](https://cloud.githubusercontent.com/assets/1375475/12778938/c8e44a46-ca65-11e5-984a-66b48a9c5a0c.png)

That ends in:

![screen shot 2016-02-03 at 11 03 52](https://cloud.githubusercontent.com/assets/1375475/12778957/da06c010-ca65-11e5-8ce6-1de2d7fce991.png)

Checking the log file in the guest machine: `vagrant ssh` and `cat /var/log/vboxadd-install.log` I see:

```
Uninstalling modules from DKMS
Attempting to install using DKMS

Creating symlink /var/lib/dkms/vboxguest/5.0.14/source ->
                 /usr/src/vboxguest-5.0.14

DKMS: add completed.
Error! Your kernel headers for kernel 3.19.0-25-generic cannot be found.
Please install the linux-headers-3.19.0-25-generic package,
or use the --kernelsourcedir option to tell DKMS where it's located
Failed to install using DKMS, attempting to install without
/tmp/vbox.0/Makefile.include.header:97: *** Error: unable to find the sources of your current Linux kernel. Specify KERN_DIR=<directory> and run Make again.  Stop.
Creating user for the Guest Additions.
Creating udev rule for the Guest Additions kernel module.
```

Have you faced similar situation?

The machine works anyway. So please close this issue when you read it. It was created just to know if anyone is facing it.

**Comment by johanjanssens** [comment]
Hello Javier, please do not use the Github issues to ask questions. If you do have a problem running the box please use either [our forum](https://groups.google.com/forum/#!forum/joomlatools-dev) or [chat room](http://gitter.im/joomlatools/dev) to get in touch with us and we are most happy to try and help you.

**Comment by javigomez** [comment]
ops! I didn't know about these resources. Thanks I'll jump there :+1:

**Comment by johanjanssens** [comment]
They are also mentioned our our contribution guidelines : http://developer.joomlatools.com/contribute.html

Thanks!
