### ISSUE TITLE
Z-Ray version is expired

### ISSUE THREAD

**Issue by javigomez** [joomlatools/joomlatools-vagrant#21]
I saw the Z-Ray link in the box home but when clicking you get to this:

![screen shot 2016-02-18 at 18 14 37](https://cloud.githubusercontent.com/assets/1375475/13151704/9f286cfc-d66b-11e5-8828-207f0691840c.png)

**Comment by javigomez** [comment]
I'm sometimes getting errors from z-ray:

<img width="527" alt="screen shot 2016-02-19 at 12 32 29" src="https://cloud.githubusercontent.com/assets/1375475/13174579/ef6505ba-d704-11e5-8bf7-8294a686f086.png">

I would do changes it, but since the version is expired you can't access to the UX to do modifications.

Probably the vagrant box could add an option to activate it or not.

**Comment by stevenrombauts** [comment]
Hi @javigomez,

We didn't get around to updating it yet and yes, it might break sometimes as it's still in (preview mode](https://www.zend.com/en/products/z-ray/z-ray-preview). 

You can disable it very easily using the [box zray:disable](https://www.joomlatools.com/developer/tools/vagrant/commands/zray/#zraydisable) command to get it out of your way.

**Comment by javigomez** [comment]
Ops, I missed that command. Thanks! :smile:
