### ISSUE TITLE
Use php-fpm, drop mod_php

### ISSUE THREAD

**Issue by tomjanssens** [joomlatools/joomlatools-vagrant#28]
Apache 2.4 can now perfectly work with php-fpm instead of the old mod_php, and is even the recommended method from now on. This will make it easier to add Nginx in the mix later on, and requires less fiddling with .so files when switching PHP versions:
- Install php-fpm
- Confiugure Apache to talk to php-fpm instead of using mod_php
- Remove the mod_phpX logic from phpmanager and always compile FPM

By installing multiple versions through the new PPA (see #69) we can then easily set a different version per vhost.

**Comment by PhilETaylor** [comment]
Awesome - cant wait to try this and replace MAMP for good :)
