### ISSUE TITLE
Rename to box

### ISSUE THREAD

**Issue by tomjanssens** [joomlatools/joomlatools-vagrant#46]
Talk about "box" instead of "vagrant" in the documentation and READMEs. Likewise, move developer.joomlatools.com/tools/vagrant.html -> box.html.

**Comment by johanjanssens** [comment]
@tomjanssens Is this still valid, since you #13 you changed the name to Joomlatools Vagrant?

**Comment by tomjanssens** [comment]
No, this issue became invalid.
