### ISSUE TITLE
Error 503 Backend fetch failed

### ISSUE THREAD

**Issue by thotmx** [joomlatools/joomlatools-vagrant#66]
I installed a fresh joomlatools vagrant but I got an "Error 503 Backend fetch failed".

The apache log only showed something like:
```
[core:notice] [pid 4983] AH00052: child pid 4989 exit signal Segmentation fault (11)
```

I tried many things but the only that worked was removing zray plugin.

I'll leave this here. Maybe it would be useful for somebody.

**Comment by johanjanssens** [comment]
Hello Hermes, please do not use the Github issues to ask questions. If you do have a problem running the box please use either [our forum](https://groups.google.com/forum/#!forum/joomlatools-dev) or [chat room](http://gitter.im/joomlatools/dev) to get in touch with us and we are most happy to try and help you. Thanks!

**Comment by thotmx** [comment]
Ok. Thanks I'll do this way in the future.

In fact, it was not a question, it was a problem solved. Maybe adding a
wiki with common problems would be useful.

On Fri, Apr 22, 2016 at 9:40 AM, Johan Janssens <notifications@github.com>
wrote:

> Hello Hermes, please do not use the Github issues to ask questions. If you
> do have a problem running the box please use either our forum
> <https://groups.google.com/forum/#!forum/joomlatools-dev> or chat room
> <http://gitter.im/joomlatools/dev> to get in touch with us and we are
> most happy to try and help you. Thanks!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomlatools/joomlatools-vagrant/issues/66#issuecomment-213452568>
>



-- 
Hermes Ojeda Ruiz

**Comment by johanjanssens** [comment]
Thanks Hermes, my apologies i missed the info that removing the zray plugin solved this issue. We will keep an eye out for this. Zray is a technology preview from Zend, it's not stable software yet and can have issues. There is not much we can do about that.
