### ISSUE TITLE
PHP 7

### ISSUE THREAD

**Issue by webchun** [joomlatools/joomlatools-vagrant#67]
Is there any chance to have php 7 installed as default? Or a php switcher maybe? I believe this will benefit developers who transitioning their code to support php7

**Comment by stevenrombauts** [comment]
Hi @webchun, you can switch to any PHP version using the [box php:use <version>](https://www.joomlatools.com/developer/tools/vagrant/commands/php/#phpuse) command. 

We ask you to not use the Github issues to ask questions. For general questions or suggestions you can use [our forum](https://groups.google.com/forum/#!forum/joomlatools-dev) or [chat room](http://gitter.im/joomlatools/dev) to get in touch with us and we are most happy to try and help you.
