### ISSUE TITLE
New PPA for PHP.

### ISSUE THREAD

**Issue by MindTooth** [joomlatools/joomlatools-vagrant#69]
Hi,

Got a message regarding a updated PPA for the PHP source.

New version https://launchpad.net/~ondrej/+archive/ubuntu/php/

Note: after installation we can automatically have apt-get update all php versions.

**Comment by johanjanssens** [comment]
Hello! For discussions, feature suggestions please use our [gitter chat](http://gitter.im/joomlatools/dev) or forums. Thanks!
