### ISSUE TITLE
Missing zip program in vagrant box

### ISSUE THREAD

**Issue by jebbdomingo** [joomlatools/joomlatools-vagrant#82]
`zip` is not pre-installed in the latest `joomlatools/box` 1.4.4

**Comment by stevenrombauts** [comment]
Solved in #45 ([13595e79](https://github.com/joomlatools/joomlatools-vagrant/commit/13595e79c6ee9fb6243d540f39382ca3b1685d26#diff-18f515a6e95b129e54d37280ed433777R18)), closing this ticket.
