### ISSUE TITLE
Disable always_populate_raw_post_data

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/joomlatools-vagrant#89]
Set `always_populate_raw_post_data` to `-1` to prevent deprecation warnings.

See: https://www.bram.us/2014/10/26/php-5-6-automatically-populating-http_raw_post_data-is-deprecated-and-will-be-removed-in-a-future-version/

**Comment by yiendos** [comment]
Marking this ticket as invalid as this configuration was removed in php 7.0:
https://www.php.net/manual/en/ini.core.php#ini.always-populate-raw-post-data

Currently rolling with:
```
$ php -v
PHP 7.1.29-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: May  3 2019 09:51:29) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.29-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```
on the box
