### ISSUE TITLE
Vagrant share no longer works

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/joomlatools-vagrant#91]
With Vagrant 1.9+ the `vagrant share --http 80` command no longer works. When browsing to the shared URL, you get an error in the browser:

````
The minute-jaguar-5508.vagrantshare.com page isn’t working

minute-jaguar-5508.vagrantshare.com is currently unable to handle this request.
HTTP ERROR 500
````

It seems it is no longer possible to connect to a port without explicitly forwarding it. This makes the connection work but the feature remains fairly unstable (slow connection):

1. Add `config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true` to Vagrantfile
2. Reload
3. Share: `vagrant share`

**Note** If you need sharing capabilities right now, it is adviced to keep running Vagrant 1.8.7 (latest 1.8.x)

Similar issues:
* https://github.com/mitchellh/vagrant/issues/7832
* https://github.com/mitchellh/vagrant/issues/3118#issuecomment-272227544
* http://stackoverflow.com/questions/41959644/how-to-share-a-vagrant-machine-with-https
* https://github.com/laravel/homestead/issues/395

**Comment by tomjanssens** [comment]
Until being fixed you can also use https://ngrok.com/ and share the box using:

`ngrok http joomla.box:80`

**Comment by stevenrombauts** [comment]
The instructions in the README work again, closing this ticket.
