### ISSUE TITLE
Joomla Patchtester not working

### ISSUE THREAD

**Issue by marcodings** [joomlatools/joomlatools-vagrant#92]
To assist in testing joomla has a patchtester the allows for easy deployment and removal of testcode associated with pull requests.
https://docs.joomla.org/Component_Patchtester_for_Testers/en

The tool will try to access github.com.

By default the joomlatools vagrant box does NOT seem to have DNS enabled, and as such making it impossible to use the patchtester

DNS needs to be added to the vagrant

as a workaround add the modify the /etc/network/interfaces
sudo vim /etc/network/interfaces
```
# add the following at the end
dns-nameservers 8.8.8.8 8.8.4.4
```

next restart the network interface
```
sudo ifdown eth0
sudo ifup eth0
```

**Comment by stevenrombauts** [comment]
Thanks @marcodings. In normal circumstances Virtualbox should just use your host machine's DNS servers but it looks like we did not add the proper flag to the Vagrantfile yet. 

However, if you can install a site using `joomla site:create` it should work. This command also connects directly to github.com.

Setting the `natdnshostresolver1` flag should solve it without having to modify `/etc/network/interfaces` ([background](http://serverfault.com/questions/453185/vagrant-virtualbox-dns-10-0-2-3-not-working)).

We will test this further in the next release. Thank you!

**Comment by stevenrombauts** [comment]
We added the `natdnshostresolver1` flag to the Vagrantfile in v1.5. Tested the Patchtester on multiple occasions, this should be working fine under all circumstances. Closing this ticket.
