### ISSUE TITLE
Issue running vagrant up on MacOS x host

### ISSUE THREAD

**Issue by dclarke-modus** [joomlatools/joomlatools-vagrant#93]
Good day:

Love your vagrant plugin for develop however, I'm having some issue running the box using `vagrant up`

     Bringing machine 'web' up with 'virtualbox' provider...
     ==> web: Checking if box 'joomlatools/box' is up to date...
     ==> web: Clearing any previously set network interfaces...
    ==> web: Preparing network interfaces based on configuration...
    web: Adapter 1: nat
    web: Adapter 2: hostonly
    ==> web: Forwarding ports...
    web: 3306 (guest) => 3307 (host) (adapter 1)
    web: 1337 (guest) => 1337 (host) (adapter 1)
    web: 22 (guest) => 2222 (host) (adapter 1)
    ==> web: Running 'pre-boot' VM customizations...
    ==> web: Booting VM...
    ==> web: Waiting for machine to boot. This may take a few minutes...
    web: SSH address: 127.0.0.1:2222
    web: SSH username: vagrant
    web: SSH auth method: private key
    ==> web: Machine booted and ready!
    [web] No installation found.
    Reading package lists...
    Building dependency tree...
    Reading state information...
    linux-headers-4.2.0-27-generic is already the newest version.
    The following packages will be upgraded:
    dkms
    1 upgraded, 0 newly installed, 0 to remove and 216 not upgraded.
    Need to get 65.7 kB of archives.
    After this operation, 2,048 B of additional disk space will be used.
    Get:1 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main dkms all 2.2.0.3-
    1.1ubuntu5.14.04.9 [65.7 kB]
    dpkg-preconfigure: unable to re-open stdin: No such file or directory
    Fetched 65.7 kB in 2min 0s (544 B/s)
    (Reading database ... 81951 files and directories currently installed.)
    Preparing to unpack .../dkms_2.2.0.3-1.1ubuntu5.14.04.9_all.deb ...  
    Unpacking dkms (2.2.0.3-1.1ubuntu5.14.04.9) over (2.2.0.3-1.1ubuntu5.14.04.5) ...
    Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
    Setting up dkms (2.2.0.3-1.1ubuntu5.14.04.9) ...
    Copy iso file /Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso into the box 
    /tmp/VBoxGuestAdditions.iso  
    mount: block device /tmp/VBoxGuestAdditions.iso is write-protected, mounting read-only
    Installing Virtualbox Guest Additions 5.0.16 - guest version is unknown
    Verifying archive integrity... All good.  
    Uncompressing VirtualBox 5.0.16 Guest Additions for Linux............
    VirtualBox Guest Additions installer
    Removing installed version 5.1.18 of VirtualBox Guest Additions...
    vboxadd.sh: Stopping VirtualBox Additions.
    Copying additional installer modules ...
    Installing additional modules ... 
    Removing existing VirtualBox DKMS kernel modules ...done.
    Removing existing VirtualBox non-DKMS kernel modules ...done.
    Building the VirtualBox Guest Additions kernel modules
    The headers for the current running kernel were not found. If the following
    module compilation fails then this could be the reason.

     Building the main Guest Additions module ...fail!
     (Look at /var/log/vboxadd-install.log to find out what went wrong)
     Doing non-kernel setup of the Guest Additions ...done.
     Installing the Window System drivers
     Could not find the X.Org or XFree86 Window System, skipping.
     An error occurred during installation of VirtualBox Guest Additions 5.0.16. Some functionality may not work as intended.
     In most cases it is OK that the "Window System drivers" installation failed.
     Starting the VirtualBox Guest Additions ...fail!
      (modprobe vboxguest failed)
      ==> web: Checking for guest additions in VM...
      web: No guest additions were detected on the base box for this VM! Guest
      web: additions are required for forwarded ports, shared folders, host only
      web: networking, and more. If SSH fails on this machine, please install
      web: the guest additions and repackage the box to continue.
      web: 
      web: This is not an error message; everything may continue to work properly,
      web: in which case you may ignore this message.
      ==> web: [vagrant-hostsupdater] Checking for host entries
      ==> web: [vagrant-hostsupdater]   found entry for: 33.33.33.58 joomlatools  
      ==> web: Setting hostname...
      ==> web: Configuring and enabling network interfaces...
      ==> web: Installing NFS client...
      ==> web: Exporting NFS shared folders...
      ==> web: Preparing to edit /etc/exports. Administrator privileges will be required...
      Password:
      ==> web: Mounting NFS shared folders...
      ==> web: Mounting shared folders...
      web: /vagrant => /Users/deanclarke/vagrant/joomla/techstack
      Vagrant was unable to mount VirtualBox shared folders. This is usually
      because the filesystem "vboxsf" is not available. This filesystem is
      made available via the VirtualBox Guest Additions and kernel module.
      Please verify that these guest additions are properly installed in the
      guest. This is not a bug in Vagrant and is usually caused by a faulty
      Vagrant box. For context, the command attempted was:
 
      mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

     The error output from the command was:

     /sbin/mount.vboxsf: mounting failed with the error: No such device

Specifically, I believe the issue is failing here:

    mount: block device /tmp/VBoxGuestAdditions.iso is write-protected, mounting read-only
    Installing Virtualbox Guest Additions 5.0.16 - guest version is unknown
    Verifying archive integrity... All good.  
    Uncompressing VirtualBox 5.0.16 Guest Additions for Linux............
    VirtualBox Guest Additions installer
    Removing installed version 5.1.18 of VirtualBox Guest Additions...
    vboxadd.sh: Stopping VirtualBox Additions.
    Copying additional installer modules ...
    Installing additional modules ... 
    Removing existing VirtualBox DKMS kernel modules ...done.
    Removing existing VirtualBox non-DKMS kernel modules ...done.
    Building the VirtualBox Guest Additions kernel modules
    The headers for the current running kernel were not found. If the following
    module compilation fails then this could be the reason.

My VirtualBox version is `5.0.16r105871` and the list of plugins vagrant has:

     vagrant-bindfs (1.0.7)
     vagrant-hostsupdater (1.0.2)
     vagrant-share (1.1.8)
     vagrant-triggers (0.5.3)
     vagrant-vbguest (0.14.2)

**Comment by johanjanssens** [comment]
Please do not use the Github issues to ask questions. If you do have a problem running the box please use either [our forum](https://groups.google.com/forum/#!forum/joomlatools-dev) or [chat room](http://gitter.im/joomlatools/dev) to get in touch with us and we are most happy to try and help you.
